version: '3.8'

services:
  vanna-ai-qa:
    build: .
    container_name: vanna-ai-qa
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma
    restart: unless-stopped
